site:
  title: Acme configuration provider
  url: https://docs.acme.com
  start_page: acme-configuration-provider::index.adoc

content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs

ui:
  bundle:
    url: https://github.com/quarkiverse/antora-ui-quarkiverse/releases/latest/download/ui-bundle.zip
    snapshot: true

runtime:
  fetch: true